---
- hosts: kube-hosts
  tasks:
  - name: disable swap
    shell: swapoff
      src: /home/cloud_user/.jenkins/workspace/build-app/target/demo-thorntail.jar 
      dest: /home/cloud_user/demo-thorntail.jar 
      
  - name: execute jar
    shell: nohup java -Dthorntail.http.port={{port}} -jar ./demo-thorntail.jar &   
