---
- hosts: test2
  tasks:
  - name: copy warbinaries
    copy:
      src: /home/cloud_user/.jenkins/workspace/build-app/target/demo-thorntail.jar 
      dest: /home/cloud_user/demo-thorntail.jar 
      
  - name: execute jar
    shell: java -Dthorntail.http.port=8181 -jar ./demo-thorntail.jar
    
      


