name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3.13.0
        with:
#          node-version: '14'
          distribution: 'temurin'
          java-version: '17'
#      - run: java -version
      - run: yum install httpd -y
#      - run: bats -v
